main: Main.Main
version: 1.5.2
name: WhiteListBot
author: Limonchegggg
api-version: 1.18
commands:
    wladd:
      description: Добавление игроков в вл
      permission: bwt.admin
    wlremove:
      description: Удаление игроков из вл
      permission: bwt.admin
    connection:
      description: Проверка подключения к базе
      permission: bwt.admin
    v:
      description: Вааниш
      permission: bwt.vanish
    bot:
      description: Команды бота
      permission: bwt.bot
    adm:
      description: Админская команда
      permission: bwt.ban
    reloadConfig:
      description: Перезагружает конфиги
      permission: bwt.configs
    item:
      description: Добавление предмета
      permission: bwt.survival.createItem
    stats:
      description: Првоерка статов
      permissiond: bwt.stats
    lvl:
      description: Уровни
      permission: bwt.admin.lvl
    hat:
      description: Шляпы на бошку
      permission: bwt.hat
    lvlcommand:
      description: Добавление уровня
      permission: bwt.commands
    database:
      description: Работа с базами
      permission: bwt.database
permissions:
    admin:
        description: метка на админа
    bwt.survival.createItem:
        description: Разрешение добавления предмета
    bwt.admin.lvl:
        description: Разрешает менять и смотреть уровни игроков
    bwt.hat:
        description: Позволяет надеть шляпу
    bwt.commands:
        description: Позволяет давать на комманды уровень
    bwt.database:
        description: Позволяет работать с базами
      